<?php
$server='192.168.100.14';
$link2 =  mssql_connect($server, 'sa', '@0X$4Z8%6I2E');
mssql_select_db('siseg_v3', $link2);

$query="INSERT INTO no_confirmados (folio, fecha, ubicacion, colonia, hora, tipo, coordenda_x, coordenada_y ,comentarios ,noco_usuario ,noco_fecha_subida ,noco_estatus)
VALUES ('44663875', '19/04/2021', '; 5TA CERRADA DE SANTA MARIA 3-A // SANTA LUCIA', 'FRACC JARDINES DE SANTA ROSA/PUEBLA/PUEBLA', '00:01:30', 'VIOLENCIA CONTRA LA MUJER', 18.967022753473657, -98.24820124579422 , 'CELL AV 141 PTE/AV 5 S, 112217, MENICONA PET QUE UN MASCULINO ESTA AGRESIVO Y, ESTA LLENA DE SANGRE, SOLICITA QUE ENVIEN UNA, UNIDAD DE POLICIA, YA SE HABIA ATENDIDO CON FOLIO :44662709 LA, PAREJA EN EL INTERIOR DE UN DOMICILIO EN COMP´LTO, ESTADO DE EBRIEDAD ,,SALE MASCULINO AGRESIVO, INDICANDO QUE ELLOS NO SOLICITARON NINGUN, APOYO..INDICA CABINA ZONA 8 : REPORTA AL LUGAR, UNIDAD VP-809 ABORDO POL.CAPITAN HERANDEZ FATIMA, ESTEFANIA Y POL. BARRIOS CANALES JORGE MANUEL..., /////, ENTERADO TELMUJER CON ESTA HORA SE TOMA, CONOCIMIENTO DE ESTE FOLIO YA QUE LA LÍNEA ESTABA, OCUPADA, SE REALIZÓ LLAMADA DE CONTACTO EN 2 OCASIONES, PERO PETICIONARIA NO CONTESTÓ. SE CIERRA FOLIO, CON NOTAS DE POLICÍA, /////', 1, '28-04-2021', 1)";
mssql_query($query,$link2);
?>
